// Generated by gencpp from file Thus_g5/modify_waypoint.msg
// DO NOT EDIT!


#ifndef THUS_G5_MESSAGE_MODIFY_WAYPOINT_H
#define THUS_G5_MESSAGE_MODIFY_WAYPOINT_H

#include <ros/service_traits.h>


#include <Thus_g5/modify_waypointRequest.h>
#include <Thus_g5/modify_waypointResponse.h>


namespace Thus_g5
{

struct modify_waypoint
{

typedef modify_waypointRequest Request;
typedef modify_waypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct modify_waypoint
} // namespace Thus_g5


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Thus_g5::modify_waypoint > {
  static const char* value()
  {
    return "478c393b4e4234c67c0fc79ff227ecab";
  }

  static const char* value(const ::Thus_g5::modify_waypoint&) { return value(); }
};

template<>
struct DataType< ::Thus_g5::modify_waypoint > {
  static const char* value()
  {
    return "Thus_g5/modify_waypoint";
  }

  static const char* value(const ::Thus_g5::modify_waypoint&) { return value(); }
};


// service_traits::MD5Sum< ::Thus_g5::modify_waypointRequest> should match
// service_traits::MD5Sum< ::Thus_g5::modify_waypoint >
template<>
struct MD5Sum< ::Thus_g5::modify_waypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Thus_g5::modify_waypoint >::value();
  }
  static const char* value(const ::Thus_g5::modify_waypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Thus_g5::modify_waypointRequest> should match
// service_traits::DataType< ::Thus_g5::modify_waypoint >
template<>
struct DataType< ::Thus_g5::modify_waypointRequest>
{
  static const char* value()
  {
    return DataType< ::Thus_g5::modify_waypoint >::value();
  }
  static const char* value(const ::Thus_g5::modify_waypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Thus_g5::modify_waypointResponse> should match
// service_traits::MD5Sum< ::Thus_g5::modify_waypoint >
template<>
struct MD5Sum< ::Thus_g5::modify_waypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Thus_g5::modify_waypoint >::value();
  }
  static const char* value(const ::Thus_g5::modify_waypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Thus_g5::modify_waypointResponse> should match
// service_traits::DataType< ::Thus_g5::modify_waypoint >
template<>
struct DataType< ::Thus_g5::modify_waypointResponse>
{
  static const char* value()
  {
    return DataType< ::Thus_g5::modify_waypoint >::value();
  }
  static const char* value(const ::Thus_g5::modify_waypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // THUS_G5_MESSAGE_MODIFY_WAYPOINT_H
