// Generated by gencpp from file Thus_g5/nav_goalRequest.msg
// DO NOT EDIT!


#ifndef THUS_G5_MESSAGE_NAV_GOALREQUEST_H
#define THUS_G5_MESSAGE_NAV_GOALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Thus_g5
{
template <class ContainerAllocator>
struct nav_goalRequest_
{
  typedef nav_goalRequest_<ContainerAllocator> Type;

  nav_goalRequest_()
    : goal()  {
    }
  nav_goalRequest_(const ContainerAllocator& _alloc)
    : goal(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::Thus_g5::nav_goalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Thus_g5::nav_goalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct nav_goalRequest_

typedef ::Thus_g5::nav_goalRequest_<std::allocator<void> > nav_goalRequest;

typedef boost::shared_ptr< ::Thus_g5::nav_goalRequest > nav_goalRequestPtr;
typedef boost::shared_ptr< ::Thus_g5::nav_goalRequest const> nav_goalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Thus_g5::nav_goalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Thus_g5::nav_goalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Thus_g5::nav_goalRequest_<ContainerAllocator1> & lhs, const ::Thus_g5::nav_goalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Thus_g5::nav_goalRequest_<ContainerAllocator1> & lhs, const ::Thus_g5::nav_goalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Thus_g5

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::Thus_g5::nav_goalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Thus_g5::nav_goalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Thus_g5::nav_goalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Thus_g5::nav_goalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Thus_g5::nav_goalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Thus_g5::nav_goalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Thus_g5::nav_goalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e8c62b390dd09eb60220ad7325cbdf7";
  }

  static const char* value(const ::Thus_g5::nav_goalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e8c62b390dd09ebULL;
  static const uint64_t static_value2 = 0x60220ad7325cbdf7ULL;
};

template<class ContainerAllocator>
struct DataType< ::Thus_g5::nav_goalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Thus_g5/nav_goalRequest";
  }

  static const char* value(const ::Thus_g5::nav_goalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Thus_g5::nav_goalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string goal\n"
;
  }

  static const char* value(const ::Thus_g5::nav_goalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Thus_g5::nav_goalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nav_goalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Thus_g5::nav_goalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Thus_g5::nav_goalRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THUS_G5_MESSAGE_NAV_GOALREQUEST_H
