// Generated by gencpp from file Thus_g5/nav_goal.msg
// DO NOT EDIT!


#ifndef THUS_G5_MESSAGE_NAV_GOAL_H
#define THUS_G5_MESSAGE_NAV_GOAL_H

#include <ros/service_traits.h>


#include <Thus_g5/nav_goalRequest.h>
#include <Thus_g5/nav_goalResponse.h>


namespace Thus_g5
{

struct nav_goal
{

typedef nav_goalRequest Request;
typedef nav_goalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nav_goal
} // namespace Thus_g5


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Thus_g5::nav_goal > {
  static const char* value()
  {
    return "85eb5661a8af1bbedc0539d77068c54e";
  }

  static const char* value(const ::Thus_g5::nav_goal&) { return value(); }
};

template<>
struct DataType< ::Thus_g5::nav_goal > {
  static const char* value()
  {
    return "Thus_g5/nav_goal";
  }

  static const char* value(const ::Thus_g5::nav_goal&) { return value(); }
};


// service_traits::MD5Sum< ::Thus_g5::nav_goalRequest> should match
// service_traits::MD5Sum< ::Thus_g5::nav_goal >
template<>
struct MD5Sum< ::Thus_g5::nav_goalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Thus_g5::nav_goal >::value();
  }
  static const char* value(const ::Thus_g5::nav_goalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Thus_g5::nav_goalRequest> should match
// service_traits::DataType< ::Thus_g5::nav_goal >
template<>
struct DataType< ::Thus_g5::nav_goalRequest>
{
  static const char* value()
  {
    return DataType< ::Thus_g5::nav_goal >::value();
  }
  static const char* value(const ::Thus_g5::nav_goalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Thus_g5::nav_goalResponse> should match
// service_traits::MD5Sum< ::Thus_g5::nav_goal >
template<>
struct MD5Sum< ::Thus_g5::nav_goalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Thus_g5::nav_goal >::value();
  }
  static const char* value(const ::Thus_g5::nav_goalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Thus_g5::nav_goalResponse> should match
// service_traits::DataType< ::Thus_g5::nav_goal >
template<>
struct DataType< ::Thus_g5::nav_goalResponse>
{
  static const char* value()
  {
    return DataType< ::Thus_g5::nav_goal >::value();
  }
  static const char* value(const ::Thus_g5::nav_goalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // THUS_G5_MESSAGE_NAV_GOAL_H
