// Generated by gencpp from file Thus_g5/vel_ctrl.msg
// DO NOT EDIT!


#ifndef THUS_G5_MESSAGE_VEL_CTRL_H
#define THUS_G5_MESSAGE_VEL_CTRL_H

#include <ros/service_traits.h>


#include <Thus_g5/vel_ctrlRequest.h>
#include <Thus_g5/vel_ctrlResponse.h>


namespace Thus_g5
{

struct vel_ctrl
{

typedef vel_ctrlRequest Request;
typedef vel_ctrlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct vel_ctrl
} // namespace Thus_g5


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Thus_g5::vel_ctrl > {
  static const char* value()
  {
    return "7d814a1679e0452bdd864dd2c3793820";
  }

  static const char* value(const ::Thus_g5::vel_ctrl&) { return value(); }
};

template<>
struct DataType< ::Thus_g5::vel_ctrl > {
  static const char* value()
  {
    return "Thus_g5/vel_ctrl";
  }

  static const char* value(const ::Thus_g5::vel_ctrl&) { return value(); }
};


// service_traits::MD5Sum< ::Thus_g5::vel_ctrlRequest> should match
// service_traits::MD5Sum< ::Thus_g5::vel_ctrl >
template<>
struct MD5Sum< ::Thus_g5::vel_ctrlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Thus_g5::vel_ctrl >::value();
  }
  static const char* value(const ::Thus_g5::vel_ctrlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Thus_g5::vel_ctrlRequest> should match
// service_traits::DataType< ::Thus_g5::vel_ctrl >
template<>
struct DataType< ::Thus_g5::vel_ctrlRequest>
{
  static const char* value()
  {
    return DataType< ::Thus_g5::vel_ctrl >::value();
  }
  static const char* value(const ::Thus_g5::vel_ctrlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Thus_g5::vel_ctrlResponse> should match
// service_traits::MD5Sum< ::Thus_g5::vel_ctrl >
template<>
struct MD5Sum< ::Thus_g5::vel_ctrlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Thus_g5::vel_ctrl >::value();
  }
  static const char* value(const ::Thus_g5::vel_ctrlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Thus_g5::vel_ctrlResponse> should match
// service_traits::DataType< ::Thus_g5::vel_ctrl >
template<>
struct DataType< ::Thus_g5::vel_ctrlResponse>
{
  static const char* value()
  {
    return DataType< ::Thus_g5::vel_ctrl >::value();
  }
  static const char* value(const ::Thus_g5::vel_ctrlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // THUS_G5_MESSAGE_VEL_CTRL_H
