// Generated by gencpp from file Thus_g5/vel_ctrlResponse.msg
// DO NOT EDIT!


#ifndef THUS_G5_MESSAGE_VEL_CTRLRESPONSE_H
#define THUS_G5_MESSAGE_VEL_CTRLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Thus_g5
{
template <class ContainerAllocator>
struct vel_ctrlResponse_
{
  typedef vel_ctrlResponse_<ContainerAllocator> Type;

  vel_ctrlResponse_()
    : vx(0.0)
    , vy(0.0)
    , w(0.0)  {
    }
  vel_ctrlResponse_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef float _vx_type;
  _vx_type vx;

   typedef float _vy_type;
  _vy_type vy;

   typedef float _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct vel_ctrlResponse_

typedef ::Thus_g5::vel_ctrlResponse_<std::allocator<void> > vel_ctrlResponse;

typedef boost::shared_ptr< ::Thus_g5::vel_ctrlResponse > vel_ctrlResponsePtr;
typedef boost::shared_ptr< ::Thus_g5::vel_ctrlResponse const> vel_ctrlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Thus_g5::vel_ctrlResponse_<ContainerAllocator1> & lhs, const ::Thus_g5::vel_ctrlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Thus_g5::vel_ctrlResponse_<ContainerAllocator1> & lhs, const ::Thus_g5::vel_ctrlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Thus_g5

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3691ef5f5de1a108d3f9cc106129c39";
  }

  static const char* value(const ::Thus_g5::vel_ctrlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3691ef5f5de1a10ULL;
  static const uint64_t static_value2 = 0x8d3f9cc106129c39ULL;
};

template<class ContainerAllocator>
struct DataType< ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Thus_g5/vel_ctrlResponse";
  }

  static const char* value(const ::Thus_g5::vel_ctrlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vx\n"
"float32 vy\n"
"float32 w\n"
;
  }

  static const char* value(const ::Thus_g5::vel_ctrlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vel_ctrlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Thus_g5::vel_ctrlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Thus_g5::vel_ctrlResponse_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THUS_G5_MESSAGE_VEL_CTRLRESPONSE_H
