// Generated by gencpp from file Thus_g5/vel_ctrlRequest.msg
// DO NOT EDIT!


#ifndef THUS_G5_MESSAGE_VEL_CTRLREQUEST_H
#define THUS_G5_MESSAGE_VEL_CTRLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Thus_g5
{
template <class ContainerAllocator>
struct vel_ctrlRequest_
{
  typedef vel_ctrlRequest_<ContainerAllocator> Type;

  vel_ctrlRequest_()
    : dx(0)
    , dy(0)
    , dth(0)
    , flag(0)  {
    }
  vel_ctrlRequest_(const ContainerAllocator& _alloc)
    : dx(0)
    , dy(0)
    , dth(0)
    , flag(0)  {
  (void)_alloc;
    }



   typedef int8_t _dx_type;
  _dx_type dx;

   typedef int8_t _dy_type;
  _dy_type dy;

   typedef int8_t _dth_type;
  _dth_type dth;

   typedef int8_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct vel_ctrlRequest_

typedef ::Thus_g5::vel_ctrlRequest_<std::allocator<void> > vel_ctrlRequest;

typedef boost::shared_ptr< ::Thus_g5::vel_ctrlRequest > vel_ctrlRequestPtr;
typedef boost::shared_ptr< ::Thus_g5::vel_ctrlRequest const> vel_ctrlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Thus_g5::vel_ctrlRequest_<ContainerAllocator1> & lhs, const ::Thus_g5::vel_ctrlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.dx == rhs.dx &&
    lhs.dy == rhs.dy &&
    lhs.dth == rhs.dth &&
    lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Thus_g5::vel_ctrlRequest_<ContainerAllocator1> & lhs, const ::Thus_g5::vel_ctrlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Thus_g5

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "223727083582ecbea99ffb87c0f4087d";
  }

  static const char* value(const ::Thus_g5::vel_ctrlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x223727083582ecbeULL;
  static const uint64_t static_value2 = 0xa99ffb87c0f4087dULL;
};

template<class ContainerAllocator>
struct DataType< ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Thus_g5/vel_ctrlRequest";
  }

  static const char* value(const ::Thus_g5::vel_ctrlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 dx\n"
"int8 dy\n"
"int8 dth\n"
"int8 flag\n"
;
  }

  static const char* value(const ::Thus_g5::vel_ctrlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dx);
      stream.next(m.dy);
      stream.next(m.dth);
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vel_ctrlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Thus_g5::vel_ctrlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Thus_g5::vel_ctrlRequest_<ContainerAllocator>& v)
  {
    s << indent << "dx: ";
    Printer<int8_t>::stream(s, indent + "  ", v.dx);
    s << indent << "dy: ";
    Printer<int8_t>::stream(s, indent + "  ", v.dy);
    s << indent << "dth: ";
    Printer<int8_t>::stream(s, indent + "  ", v.dth);
    s << indent << "flag: ";
    Printer<int8_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THUS_G5_MESSAGE_VEL_CTRLREQUEST_H
